# Generated by Django 4.2.2 on 2023-07-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('category_name_ar', models.CharField(max_length=150)),
                ('category_picture', models.TextField()),
                ('category_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes_name', models.CharField(max_length=255)),
                ('shoes_name_ar', models.CharField(max_length=255)),
                ('shoes_description', models.TextField()),
                ('shoes_description_ar', models.TextField()),
                ('shoes_picture', models.TextField()),
                ('shoes_price', models.FloatField()),
                ('shoes_discount', models.IntegerField(default=0, null=True)),
                ('shoes_date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.category')),
            ],
        ),
    ]
